name: zoesync
description: "zoesync"

publish_to: 'none' # This is fine for private packages; remove if publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Adjusted to ensure compatibility with Dart 3.x and Flutter

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  cupertino_icons: ^1.0.8  # Correct placement for iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Correct lint package for good coding practices

flutter:
  uses-material-design: true  # Ensures material icons are included

  # If you need to add assets like images, uncomment and adjust the following section:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts, uncomment and adjust the following section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
